### ISSUE TITLE
Index overflow in mask generation

### ISSUE THREAD

**Issue by DzReal** [DzReal/Pocket#12]
```
Traceback (most recent call last):
  ...
  ...
  File "/home/fred/pkgs/Pocket/pocket/models/interact_rcnn.py", line 412, in forward
    box_pair_features = self.box_pair_pooler(features, boxes_h, boxes_o)
  File "/home/fred/miniconda3/envs/fconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fred/pkgs/Pocket/pocket/ops/box_pair_poolers.py", line 333, in forward
    boxes_2[idx_in_level].clone()
  File "/home/fred/pkgs/Pocket/pocket/ops/box_pair_poolers.py", line 269, in construct_masks_for_box_pairs
    generate_binary_masks(boxes_1[:, 1:], *spatial_size),
  File "/home/fred/pkgs/Pocket/pocket/ops/masks.py", line 37, in generate_binary_masks
    return generate_masks(boxes, h, w)
RuntimeError: select(): index 200 out of range for tensor of size [308, 200] at dimension 1 
(select at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/ATen/native/TensorShape.cpp:458)
  ...
  ...
```
Method `pocket.ops.generate_binary_masks` appears to be working correctly. And the bounding box coordinates have been clamped based on the dimension of the masks.

**Comment by DzReal** [comment]
This has been resolved by filtering out low-confidence detections prior to constructing box pairs, although the reason of the issue remains unknown. It is suspected that some low-confidence detections have unrealistic coordinates
